### ISSUE TITLE
Bug: built-in connectors not visible in UI

### ISSUE THREAD

**Issue by nadilas** [ConduitIO/conduit#1882]
### Bug description

This might be a question rather... when starting conduit, the UI is not showing the built-in connectors. Is this expected behavior?

![CleanShot 2024-10-04 at 21 02 35@2x](https://github.com/user-attachments/assets/01809961-b10d-4f86-ab46-3b71eff76b37)

### Steps to reproduce

1. run conduit
2. new pipeline
3. new source
4. no built-in connectors available

### Version

0.11.1 darwin/arm64

**Comment by hariso** [comment]
Hey @nadilas! Welcome to Conduit!:)

You're right in the sense that it's a bug. However, we've deprecated the UI and we'll completely remove it pretty soon. I recommend that you use the [pipeline configuration files](https://conduit.io/docs/pipeline-configuration-files/getting-started) instead, since that's the recommended (and easiest) way to create pipelines.

The team will (probably today) discuss this and we'll decide whether or not to fix this bug (depending on when exactly we'll remove the UI).

Let us know if you need something more!

**Comment by nadilas** [comment]
Thanks @hariso, I agree with @nickchomey that you should not spend the effort on this as well then. We’ll go recommended route. 👍

**Comment by raulb** [comment]
Thank you all for chiming in and your understanding. We need to make sunsetting the UI while producing a great DevEx via a CLI a priority.  🙏 

This is a [design document](https://github.com/ConduitIO/conduit/discussions/1642) I put together some time ago which I'm planning to revisit once we tackle the Conduit CLI. If you have the time, it'd be much appreciated that you can look at it.

Thanks again.
