### ISSUE TITLE
Feature: Add creation and modification timestamp to objects

### ISSUE THREAD

**Issue by lyuboxa** [ConduitIO/conduit#202]
### Feature description

This potentially collapses multiple feature requests together, but I'd like to see creation and modification timestamps
on the first class objects, like connectors, pipelines, processors etc.

This will help out-of-bound changes be detected from automation systems that persist some kind of state.

**Comment by lovromazgon** [comment]
@lyuboxa we need some clarifications:
1. Would it be useful to have the modification timestamp _only_ on the pipeline object and update it every time anything related to that pipeline changed (e.g. a processor config or a connector config), or would you expect to have separate modification timestamps for each entity?
2. If we go with separate timestamps, would you expect the modification timestamp of the pipeline to be updated if a connector configuration was updated? (Technically the connector entity changed and not the pipeline)

**Comment by lovromazgon** [comment]
Good point, so this issue is concerned only with changes to the configuration of an entity, and each entity (pipeline, connector, processor) should get a timestamp field that is updated every time the configuration changes.

If we need something similar for the state changes in a pipeline we should tackle that separately.
