### ISSUE TITLE
Make it possible to create a Kafka connector plugin from the UI

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit#244]
### Feature description

It should be possible to create a Kafka connector plugin from the UI. The path to the plugin will be `pkg/plugins/kafka-connector-plugin`.

**Comment by lovromazgon** [comment]
@hariso is this feature talking about adding https://github.com/conduitio/conduit-kafka-connect-wrapper? Because that's going to be a problem - we don't ship Conduit with the plugin so we can't hardcode it in the UI, and the plugin API won't return the specs for the plugin because it only returns them for builtin plugins right now.

**Comment by hariso** [comment]
@lovromazgon Yes, this is about the wrapper. Looks like the best option we have now is to simply add the wrapper connector via the HTTP API. In that case we can probably add something to the docs, explaining how to add a standalone plugin (for now).
