### ISSUE TITLE
DLQ: API

### ISSUE THREAD

**Issue by lovromazgon** [ConduitIO/conduit#715]
Update the pipeline grpc service to include methods for retrieving and updating the DLQ config. The new methods should be mapped to these endpoints:

- `PUT /v1/pipelines/{id}/dead-letter-queue`
- `GET /v1/pipelines/{id}/dead-letter-queue`

Make sure that the DLQ config is validated, including plugin and settings (same as in a normal connector).

**Comment by hariso** [comment]
How about deleting a DLQ btw?

**Comment by lovromazgon** [comment]
Deleting a DLQ means updating the pipeline config and removing the `plugin` and `settings` fields (well, setting them to empty values).

**Comment by hariso** [comment]
WDYT about having that in a DELETE endpoint?

**Comment by lovromazgon** [comment]
Well the DLQ is currently meant to be part of the pipeline config, the pipeline config is updated in the `PUT`. It seems strange to me that part of the config could be changed with a `DELETE` request 😕 Or in other words - if we had a `DELETE` endpoint for the DLQ, I'd expect to see a `CREATE` and `PUT` endpoint specifically for creating and updating the DLQ. I was contemplating this in the design, would you prefer such a design? For example:
- `POST /v1/pipelines/{id}/dlq`
- `PUT /v1/pipelines/{id}/dlq`
- `DELETE /v1/pipelines/{id}/dlq`

**Comment by hariso** [comment]
IMHO, the DLQ CRUD operations through the pipelines endpoint make sense. On the other hand, it looks like we can view DLQ as resources (that's why I was asking about delete endpoint, I was wondering if there's something special about DLQs I missed). So, at least to me, that second option you mentioned is something I personally would prefer, and it would also make them more alike connectors and processors. It would also be easier to work with the requests, as they would contain only the DLQ configs.

**Comment by lovromazgon** [comment]
We discussed this in a call today and decided to go with 2 methods, one for retrieving the DLQ config and one for updating it. The design document and issue description were updated to reflect the decision.
